language: java
jdk:
 - openjdk8

before_install:
 - git clone https://github.com/informatici/openhospital-core.git
 - cd openhospital-core
 - mvn clean install -DskipTests=true
 - cd -
install: true
script: 
 - mvn clean package -DskipTests=true
