language: java
jdk:
 - openjdk8

before_install:
 - git clone https://github.com/informatici/openhospital-core.git --branch OP-102_master-refactoring-for-api
 - cd openhospital-core
 - mvn clean install -DskipTests=true &>/dev/null
 - cd -
install: true
script: 
 - mvn clean package -DskipTests=true
